### ISSUE TITLE
External images in notes don't work

### ISSUE THREAD

**Issue by maxb2** [dungeon-revealer/dungeon-revealer#1059]

**Comment by n1ru4l** [comment]
Can you clarify that more? You mean with the markdown syntax? `![](https://images.pexels.com/photos/104827/cat-pet-animal-domestic-104827.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500)`


`![](https://images.pexels.com/photos/104827/cat-pet-animal-domestic-104827.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500)

**Comment by n1ru4l** [comment]
It is now possible on master 🚢
