### ISSUE TITLE
Tool switches when typing token names containing numbers

### ISSUE THREAD

**Issue by cbaijens** [dungeon-revealer/dungeon-revealer#1080]
When typing a token name which contains a number the active Tool switches to the corresponding number:
1. Select the Token-tool and drop a token
2. Rename it to token 2
3. Your active tool switches to Brush (tool 2)

This is can be confusing when dropping down a dozen of skeletons numbered Skel1-12 and losing the Token tool focus each time.

**Comment by n1ru4l** [comment]
Seems like a conflict between

https://github.com/dungeon-revealer/dungeon-revealer/blob/1df14be99562f88cf21d63c2740002a2886c4c66/src/dm-area/dm-map.tsx#L768-L805


https://github.com/dungeon-revealer/dungeon-revealer/blob/1df14be99562f88cf21d63c2740002a2886c4c66/src/token-context-menu.tsx#L114-L116
