### ISSUE TITLE
fine-tune pinch gesture/mouse wheel zoom speed

### ISSUE THREAD

**Issue by n1ru4l** [dungeon-revealer/dungeon-revealer#1089]
From Discord:

> Alder Agilao: Hi. Zooming on an iPad is incredibly difficult, it zooms and zooms out way to much. Any better way to control? Using an iPad to out to a tv for my group

>jeepinbird: I second this. Pinch zooming goes really fast but using the buttons works great.

**Relevant code:**

https://github.com/dungeon-revealer/dungeon-revealer/blob/3da9d6add384babdd4f12b7dafe657a1414dfa47/src/map-tools/drag-pan-zoom-map-tool.tsx#L68

https://github.com/dungeon-revealer/dungeon-revealer/blob/3da9d6add384babdd4f12b7dafe657a1414dfa47/src/map-tools/drag-pan-zoom-map-tool.tsx#L91

**Comment by maxb2** [comment]
The exponential function might be the problem 🙈

**Comment by maxb2** [comment]
My guess is that the scroll wheel on a mouse changes in discrete and predictable steps, while the pinch gesture can vary a lot. The exponential function will wildly exaggerate whatever `wheel` is doing.

**Comment by n1ru4l** [comment]
The `wheel` variable does have either the value `-1` or `1` for both wheel and mouse zoom. There is not really a right speed, only too fast or too slow, so I feel it is a bit of a hard task to figure out the "correct" value, especially since I did not perceive stuff as too fast 😅

**Comment by maxb2** [comment]
Hmm, maybe the pinch gesture has a higher sample rate than a wheel scroll and that leads to the difference in perceived speeds.
