### ISSUE TITLE
Token Title only accepted after pressing enter

### ISSUE THREAD

**Issue by GioDel** [dungeon-revealer/dungeon-revealer#1161]
Hi,

thanks for the nice token image feature with the good cutting ans scaling I really like that! There is one part where I don't know if it's intended behavior or not:

Whenever I enter a token title and move on to the next token the title of the prvious token is not shown. And when I enter that token again the title is not changed. 

The token title is is only kept when when prssing enter after entering the title. Is this as intended or a bug?

I'm using Chrome Version 89.0.4389.90.

Thanks!
Giovanni

**Comment by n1ru4l** [comment]
This is currently the intended behaviour of the underlying library used (https://github.com/pmndrs/leva). A more desired behaviour would be either debounced (e.g. update UI after 100ms of latest key invocation) or throttled (update UI every 100ms between keystrokes). I am in contact with the maintainer regarding alternative state update strategies.
