### ISSUE TITLE
Add ability to add a compass rose as overlay to the map (overlays fog of war)

### ISSUE THREAD

**Issue by ChriD** [dungeon-revealer/dungeon-revealer#1169]
Some maps do not have a compass rose. So it would be nice to have the ability to add a compas rose (in fact a image) as overlay.
Yes we could add the compas rose to the map, but then the fog has to be revealed there and that doesnt look sexy.
So it would be cool to have a button on the toolbar which opens a pupup wheer we can upload a compas image file for that given map and that there are settings to rotate the compas node and maybe to move it via mouse

**Comment by maxb2** [comment]
Couldn't you upload a compass rose as a normal token?

**Comment by ChriD** [comment]
Due to the fact that the token images are above the fog of war that would be possible, but are the token images rotatable? If not i'd have  to have 4 rose images.  No problem at all. I can live with that. This issue can be closed. 
Thanks!

**Comment by n1ru4l** [comment]
nope but rotation shouldnt be to hard to implement 🤔

**Comment by n1ru4l** [comment]
Hey, @ChriD I will close this issue in favor of https://github.com/dungeon-revealer/dungeon-revealer/issues/1364. This should allow adding a compass via a token.
