### ISSUE TITLE
Board Game Table Mode

### ISSUE THREAD

**Issue by ChriD** [dungeon-revealer/dungeon-revealer#1186]
I do not want to see the SR toolbar on the client 
Neither i doo not want to see the "Search" icon
So it would be nice if there is a setting that's called maybe like this: "Board Game Table Mode"

If this setting is activated, only the map is there, nothing else. The actions can be triggered by the hotkeys, or we can toogle the mode by a hotkey.

**Comment by n1ru4l** [comment]
This can already be solved: https://github.com/dungeon-revealer/dungeon-revealer/wiki/Getting-Started#hide-chat--note-ui
