### ISSUE TITLE
Add Access-Control-Allow-Origin Headers?

### ISSUE THREAD

**Issue by ChriD** [dungeon-revealer/dungeon-revealer#1188]
I have a problem finding the dungeon-revealer webserver by polling the ip and port via js from an external source  due CORS restrictions. Any ideas how to prevent this?

**Comment by n1ru4l** [comment]
Cant, you have a proxy in front of it?

**Comment by ChriD** [comment]
i ended up disabling the web security for the chrome kiosk browser. I think thats the best solution for me

**Comment by n1ru4l** [comment]
Cool gonna close this for now! For advanced use-cases a proxy might be the solution
