### ISSUE TITLE
Unable to write in chat 

### ISSUE THREAD

**Issue by Bjoern-B** [dungeon-revealer/dungeon-revealer#1205]
We noticed today that for some reason some of us a disconnecting from the chat while still seeing the map and all, when they disconnect they cant write in chat anymore and if they then reload they are connected for like 30 seconds in which they can write and then the disconnect message comes in the chat again and they again cant write anything.

**Comment by n1ru4l** [comment]
Is this happening with version 1.13? Can you describe your setup? Are you behind some kind of load balancer? Is there some suspicious behaviour visible on the network tab of the dev tools?

**Comment by Bjoern-B** [comment]
Yes you can reproduce it if you just open an instance and then reload then wait about 30 sec and you will disconnect basicly you connect twice and the disconnect takes a bit of time and happens when you are already reconnected
No it didnt start with 1.13 we just tested it today where the problem was

**Comment by Bjoern-B** [comment]
Im using apache with ProxyPass to forward them to the server

**Comment by n1ru4l** [comment]
After some debugging this seems to be happening when the WebSocket connection from the client cannot be established due to a misconfigured proxy.

This pops up in the Browser Console on the clients
````
websocket.js:87 WebSocket connection to 'wss://XXXXXXXXXXXXXXX/api/socket.io/?EIO=4&transport=websocket&sid=PLZWhrZNhlcgnlYXAAB0' failed:
````

Socket.io should fallback to polling, it might be possible that this construct somehow causes these issues.

**Comment by n1ru4l** [comment]
I checked today by disabling WebSockets completely and it seems like this is no longer an issue (likely fixed by updating Socket.io version some time ago). I think we can close this for now.

If anyone experiences this again in the future feel free to open a new issue.,
