### ISSUE TITLE
Additional Drawing Layer

### ISSUE THREAD

**Issue by ChriD** [dungeon-revealer/dungeon-revealer#1259]
It would be nice to have a "drawing layer" wher the dm can draw simple stuff for e.g hidden doors.
I can use tokens for now as a workaround

**Comment by n1ru4l** [comment]
Duplicate of https://github.com/dungeon-revealer/dungeon-revealer/issues/1259

**Comment by maxb2** [comment]
This *is* #1259 😂

**Comment by n1ru4l** [comment]
😂 😂 😂 

Duplicate of https://github.com/dungeon-revealer/dungeon-revealer/issues/23
