### ISSUE TITLE
Token image: Upload new image: cannot change zoom more than once

### ISSUE THREAD

**Issue by wirmar** [dungeon-revealer/dungeon-revealer#1269]
When uploading a new token image the zoom slider can only be changed once, after which it is stuck.

https://user-images.githubusercontent.com/9307361/117334177-f941cb00-ae99-11eb-89ec-a044782b9c11.mp4

**Comment by n1ru4l** [comment]
This should be fixed on master and was an issue with chakra ui https://chakra-ui.com/changelog#04-05-2021

I will release a patch release change this weekend.
