### ISSUE TITLE
drop pkg; build binaries with caxa

### ISSUE THREAD

**Issue by n1ru4l** [dungeon-revealer/dungeon-revealer#1296]
pkg is currently blocking us from upgrading to newer Node.js versions.

Caxa is an alternative that is simpler than pkg and would allow us to use any Node.js version without having to wait for upstream issues. @maxb2 is pushing ARM support for caxa over here: https://github.com/leafac/caxa, on that, is finished we can migrate.

List of things we can do after we dropped pkg:

- Use Node 14 for binaries
- Remove uuid dependency in favor of [`crypto.randomUUID`](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V14.md#uuid-support-in-the-crypto-module)
- fix es module imports (e.g. fp-ts -> `fp-ts/lib/Either` => `fp-ts/Either`)
- replace express with [`tinyhttp`](https://github.com/talentlessguy/tinyhttp) -> less dependencies

**Comment by maxb2** [comment]
Related #1115
