### ISSUE TITLE
Token label text size different in DM view and Payer view

### ISSUE THREAD

**Issue by k3tw13z3l** [dungeon-revealer/dungeon-revealer#1301]
I noticed a difference in the token label text size,  in the DM and Player view...

DMview:
![DMview](https://user-images.githubusercontent.com/30986211/118469732-49285980-b706-11eb-9b02-f28c9fac1265.png)
Playerview
![Playerview](https://user-images.githubusercontent.com/30986211/118469758-4fb6d100-b706-11eb-8a87-01cbe5394e36.png)

**Comment by n1ru4l** [comment]
Can you share your map image dimensions?

**Comment by k3tw13z3l** [comment]
I think it is:
$ file map.jpg
map.jpg: JPEG image data, JFIF standard 1.01

hmm...
$ file fog.live.png
fog.live.png: PNG image data, 1100 x 864, 8-bit/color RGBA, non-interlaced
:smile:

**Comment by n1ru4l** [comment]
Can you also share the dimensions of the map.jpg? The folg might differ from the original image

**Comment by k3tw13z3l** [comment]
It is the same. My vps 'file' did not reveal the dimensions, but the one on my laptop does:

$ file map.jpg                                                                                                                                                                                                           
map.jpg: JPEG image data, JFIF standard 1.01, aspect ratio, density 72x72, segment length 16, Exif Standard: [TIFF image data, big-endian, direntries=2, orientation=upper-left], baseline, precision 8, 1100x864, components 3
