### ISSUE TITLE
Token rotation should be in degrees

### ISSUE THREAD

**Issue by maxb2** [dungeon-revealer/dungeon-revealer#1402]
As much as I love radians, the rotation slider should probably be in units of degrees since most people think that way.
![Screenshot from 2021-06-28 11-25-12](https://user-images.githubusercontent.com/9096667/123671195-9fa7ae00-d803-11eb-8298-5e46f3e4b78c.png)

**Comment by n1ru4l** [comment]
I agree, should be pretty easy to implement
