### ISSUE TITLE
DM Movable UX Dialogs (Suggestion)

### ISSUE THREAD

**Issue by thorgod** [dungeon-revealer/dungeon-revealer#153]
I noticed during my last game. The bottom UX seemed to get in the way for my larger maps.

![image](https://user-images.githubusercontent.com/13910170/63964686-7cb3e380-ca4c-11e9-8a20-7ce9d16a8303.png)

It would nice to make the UX box's drag-able/movable so that I can get to the areas hidden by the UX.

**Comment by n1ru4l** [comment]
We decreased the size for now.
