### ISSUE TITLE
Question: Usage of docker image via QNAP ContainerStation

### ISSUE THREAD

**Issue by GioDel** [dungeon-revealer/dungeon-revealer#1535]
I just started the latest docker image on QNAP NAS im my local network. So when calling the endpoints for the players and the dm the start page shows up. So basically it works.

But I would like to set the different parameters mentioned in the docker section of the README.me file like passwords and directory where images are stored. Do you have an idea how this can be achieved?

Thanks!
GDK

**Comment by maxb2** [comment]
Assuming you're using the GUI to start your container, you need to add environment variables and folder mounts in the Advanced Settings. See [this tutorial](https://www.linuxserver.io/blog/2017-09-17-how-to-setup-containers-on-qnap).
