### ISSUE TITLE
import map via drag and drop/url

### ISSUE THREAD

**Issue by n1ru4l** [dungeon-revealer/dungeon-revealer#159]
This went missing during the react rewrite, simply dragging an image file into the browser window is very convenient. Also, directly importing a map via a URL would be a nice feature.

(Hook for Dropzone: https://codesandbox.io/s/usedropzone-6ykrj?fontsize=14&module=%2Fsrc%2FuseDropzone.js)

We could even go further and define a map format (e.g. simple zip with map image and `settings.json`) that allows sharing maps with predefined grids (and in the future also objects?)

**Comment by thorgod** [comment]
Import/Export !!! Nice idea!

**Comment by apclary** [comment]
Agree, good idea.
