### ISSUE TITLE
Editing note links throws a graphql error

### ISSUE THREAD

**Issue by maxb2** [dungeon-revealer/dungeon-revealer#1591]
If you are editing the url part of a markdown link, `[](here)`, the terminal starts throwing graphql errors:
```
Error: Unexpected error value: [{ value: undefined, context: [Array], message: undefined }]
    at locatedError (/workspaces/maxb2/node_modules/graphql/error/locatedError.js:23:78)
    at /workspaces/maxb2/node_modules/graphql/execution/execute.js:479:52
    at async Promise.all (index 0)
``` 
Nothing appears to break because of it though.

**Comment by n1ru4l** [comment]
The error is caused because it tries to load a note via id that does not yet exist. https://github.com/dungeon-revealer/dungeon-revealer/pull/1596 should address this as a temporary workaround. The notes loading module needs some refactoring, as this can happen in several places.
