### ISSUE TITLE
Take over file name for token image upload

### ISSUE THREAD

**Issue by GioDel** [dungeon-revealer/dungeon-revealer#1594]
Currently when uploading a new image to the token image library I have to enter a name manually. 

Similar as the map upload I would like to have the name beeing defaulted from the file name. E.g. file with name "Big bad guy.jpeg" should result into name proposal "Big bad guy". Maybee this could be taken over for all available file/image uploads (if there are more)

What do you think of that idea?

Thanks!
Gio

**Comment by maxb2** [comment]
That sounds like a good idea. I'll look into implementing it.
