### ISSUE TITLE
Some maps become unavailable in UI after update from 1.16.0 to 1.17.0

### ISSUE THREAD

**Issue by petertrr** [dungeon-revealer/dungeon-revealer#1609]
After I start a docker container from v1.17.0 tag with existing data directory mounted, not all maps are available in the UI. It happens both in Firefox and in Chrome. If I roll back image version, then all maps become available again. All files are available in the filesystem, but for some reason dungeon-revealer doesn't see them.

I suspect that it has something to do with the new GraphQL API from https://github.com/dungeon-revealer/dungeon-revealer/commit/8c93f2ac198b8185061eced259ee181f65cb4356, but I'm not familiar enough with it to investigate. The only difference I can see in logs in the following message:
```
[LiquidJS] `fs.dirname` is required for relativeReference, set relativeReference to `false` to suppress this warning, or provide implementation for `fs.dirname`
```

Data directory is in use since some very old versions of dungeon-revealer, so maybe there has been some change in data storage format some time ago.

---
On a side note, there is also a message `This development version is undefined commits ahead of v1.17.0!` from `dungeonrevealer/dungeon-revealer:v1.17.0`, which was absent in the image v1.16.0.

**Comment by n1ru4l** [comment]
Fixed by https://github.com/dungeon-revealer/dungeon-revealer/issues/1609
