### ISSUE TITLE
Can't install dependencies on Apple M1 (sqlite3)

### ISSUE THREAD

**Issue by nicroto** [dungeon-revealer/dungeon-revealer#1629]
Hi,

I'm trying to build the dungeon-revealer from source but on `npm install` - I get an (http) error 403 during the installation of sqlite3. I think this is the problem, basically [described on SO](https://stackoverflow.com/questions/67928866/cannot-download-node-sqlite34-2-0-node-pre-gyp-error-tried-to-download403-a). Seems the accepted answer is there is no support for node v16, but in the docs here it says this is what should be used?

Cheers!

**Comment by nicroto** [comment]
Actually, here is the problem: https://github.com/TryGhost/node-sqlite3/issues/1616#issuecomment-1159154961

**Comment by nicroto** [comment]
I just made a PR with a fix.

**Comment by defaude** [comment]
This issue should be closed now, right? I just `npm install`ed on a M1 machine without any issues :)

**Comment by nicroto** [comment]
Yup, I believe the PR was merged. Closing. Sorry I haven't done so at the time.
