### ISSUE TITLE
Persist Dice Macros

### ISSUE THREAD

**Issue by flyswatta** [dungeon-revealer/dungeon-revealer#1640]
Running dungeon revealer on linux and unable to persist dice macros beyond restarts/browser connections.  Potentially have a file on the system that could be loaded during runtime?

**Comment by maxb2** [comment]
The "Dice Roll Notes" section is not meant to persist.

However, you can create a new note on the DM screen containing the macros that will persist. You can also make the note visible to players who can access it through the Notes tab on the bottom.
