### ISSUE TITLE
Map Notes

### ISSUE THREAD

**Issue by n1ru4l** [dungeon-revealer/dungeon-revealer#181]
It would be awesome if the DM could position a token in each area on a map. Upon clicken on the token a sidebar opens with some notes related to that location, the DM could write down a text he wants to read to the players or the enemies that are present in that location or the items available.

This would be very handy for preparing modules without having to flick through the book all the time.

Of course, those tokens (and the info) should only be visible to the DM.

**Comment by thorgod** [comment]
Probably to advanced but if we had a wiki system, you could link tokens or pens to the wiki page. Just throwing it out there to get your creative juices flowing. 

Something like Legend Keeper!
https://www.youtube.com/watch?v=VNP2B1tExNg&t=1s

**Comment by n1ru4l** [comment]
@thorgod Legendkeeper seems pretty cool! In the future, we might move into that direction for sure!

For now, I would like to keep the first implementation simple.

I thought about adding a type to each draggable token on the map. E.g. `entity` and `area`. By clicking on an `area` token a box pops up on the right of the screen. The DM can then add notes via markdown (toggle between edit and view mode).

A huge bonus would be the possibility to drag images into the editor. That could even be combined with #171. In the view mode we could add a share with players button to each media element referenced in the description 🤔.

**Comment by thorgod** [comment]
Yes I think legend keeper is a huge stretch goal, probably out of scope. But in case the project wanted to move in that direction we could keep things open. 

Would the notes be visible to the players or only the DM?

**Comment by n1ru4l** [comment]
@thorgod For the first iteration I only have notes for the DM in mind, however, we can do some kind of a share functionality later, or even player notes.
