### ISSUE TITLE
Setting env DM_Password sets auth on player area [docker]

### ISSUE THREAD

**Issue by AlchemicalAgent** [dungeon-revealer/dungeon-revealer#208]
When running latest and dev docker files setting an environment variable for DM_Password causes authentication on both /dm and the player directory (with password set to DM_Password variable). Leaving the variable unset allows access to all files as expected behavior.

docker run -e DM_PASSWORD=test -it -p 80:3000 --name mapForgotten -v $PWD/data:/usr/src/app/data -d apclary/dungeon-revealer:dev

**Comment by maxb2** [comment]
This happens with the executables too.
