### ISSUE TITLE
Travis environment variables missing

### ISSUE THREAD

**Issue by n1ru4l** [dungeon-revealer/dungeon-revealer#215]
https://travis-ci.com/dungeon-revealer/dungeon-revealer

The build is currently failing due to:

```bash
The command "echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin" exited with 1.
```

I am pretty sure the same applies to publishing github releases.

This is all caused by our migration to the organization.

@apclary could you please add the environment variables 😇

**Comment by apclary** [comment]
Will do. Unfortunately I don't know my docker hub password (I assume it wants the raw password and not a key) and the docker hub password reset page is not working for me. I'll try again tonight.

**Comment by n1ru4l** [comment]
Let me know 😊I will release 1.4.1 once that is done!

**Comment by apclary** [comment]
I had set it, but I must have fat fingered it. I got the urge to check how things were going and noticed the build was failing. I reset the password again and I see the login succeeded when I restarted your latest master build.
