### ISSUE TITLE
Make useable with raspbian / raspberry pi

### ISSUE THREAD

**Issue by hinjodragonfly** [dungeon-revealer/dungeon-revealer#256]
Hey!

Wanted to humbly suggest, if its not a huge amount of work, to make this great project also useable with devices with ARM-processors.

I just built a portable digital table-top for DnD and nothing - really nothing - beats dungeon-revealer in useability for battle maps. Exept that I can't use it with the raspberry. =)

Thank you so much for your great work so far!

**Comment by maxb2** [comment]
It is possible to run dungeon-revealer on raspbian, if you're willing to get your hands dirty. You need to setup node, npm and yarn on the raspi and then run the server as described in [Contributing](https://github.com/dungeon-revealer/dungeon-revealer/blob/master/CONTRIBUTING.md).

Open a terminal and run:
```
# Install node.js and npm 
sudo apt install nodejs npm   
# Install yarn
curl -o- -L https://yarnpkg.com/install.sh | bash   
git clone https://github.com/dungeon-revealer/dungeon-revealer.git 
git checkout v1.5.0
yarn install  # At the end, this will try to build binaries for x86 machines and will fail. 
```
If you want to run from source, then use `yarn start`. Otherwise, the compiled executable is `bin/dungeon-revealer-linux` which you can move anywhere you like.

v1.5.0 on the raspi shows a black screen when you go to `<IP_ADDRESS>:3000` as directed. You can get to the DM area by navigating to `<IP_ADDRESS>:3000/dm`. Previous versions do not require this extra step.

Good Luck! I'd love to see the portable tabletop.

**Comment by hinjodragonfly** [comment]
> It is possible to run dungeon-revealer on raspbian, if you're willing to get your hands dirty. You need to setup node, npm and yarn on the raspi and then run the server as described in [Contributing](https://github.com/dungeon-revealer/dungeon-revealer/blob/master/CONTRIBUTING.md).
> 
> Open a terminal and run:
> 
> ```
> # Install node.js and npm 
> sudo apt install nodejs npm   
> # Install yarn
> curl -o- -L https://yarnpkg.com/install.sh | bash   
> git clone https://github.com/dungeon-revealer/dungeon-revealer.git 
> cd dungeon-revealer
> git checkout v1.5.0
> yarn install  # At the end, this will try to build binaries for x86 machines and will fail. 
> yarn start
> ```
> 
> Anytime you want to run dungeon-revealer, just go back to that folder and run `yarn start`.
> 
> v1.5.0 on the raspi shows a black screen when you go to `<IP_ADDRESS>:3000` as directed. You can get to the DM area by navigating to `<IP_ADDRESS>:3000/dm`. Previous versions do not require this extra step.
> 
> Good Luck! I'd love to see the portable tabletop.

Thank you. I will try that - I've got little knowledge about any Linux usage and such, and I wasn't able to get yarn to run properly before, but it's definitely worth looking into it again!

**Comment by maxb2** [comment]
I'll keep looking into releasing an arm executable so you don't have to run from source every time. Travis-CI runs on x86 and can't compile arm code in a simple manner.

**Comment by hinjodragonfly** [comment]
Wohoooo it worked. Thank you so much.

Also my setup: very basic screem in wood with a handle to carry. Now i only need to fit the raspberry into the back and cover it.

The raspberry will be the server but ofc display the player side. My tablet has the dm side. Its sooo awesome. Dungeon revealer rocks ;)
![20191218_201038](https://user-images.githubusercontent.com/58919182/71115957-68e6e580-21d3-11ea-853a-5f63be61bcda.jpg)
![20191218_200823](https://user-images.githubusercontent.com/58919182/71115958-68e6e580-21d3-11ea-917d-d17a5e1d81c6.jpg)
![20191218_201046](https://user-images.githubusercontent.com/58919182/71115959-697f7c00-21d3-11ea-9999-364bb6e52129.jpg)

**Comment by maxb2** [comment]
The next release (>v1.5.0) will include an executable for armv7 via #261. You can use it instead of running from source as above. Keep building cool stuff!

**Comment by apclary** [comment]
Great work by the way!

**Comment by hinjodragonfly** [comment]
Awesome! Thank you so much.

Just erm so I know when to recheck - when do new releases happen? I know you all do this in your free time and I absolutely don't want to annoy anybody =). Is there any kind of cycle or should I just check monthly or somesuch.

Thanks again for the great effort and...ive been using dungeon revealer now for 6 or 7 sessions DMing D&D and its just wonderful <3

**Comment by maxb2** [comment]
I don't know when v1.6.0 is coming out (see #212 for progress). Most of the development is done by @n1ru4l these days. Releases depend on his time to contribute. The watch button has the option to be notified when new releases come out. For now, I added an arm binary that I compiled locally to the [v1.5.0](https://github.com/dungeon-revealer/dungeon-revealer/releases/tag/v1.5.0) release page.

**Comment by n1ru4l** [comment]
@hinjodragonfly hearing this makes me really happy 😌 I will try to cut a new release by the end of the month, for now you could build it yourself or use the 1.5.0 release.

**Comment by hinjodragonfly** [comment]
Hello people...
I posted this in the closed issue cause I believe its just that I am to stupid to understand. Maybe I could bother you for the time to look at this @maxb2 @n1ru4l . After COVID-19 I finally wanted to use my setup and as there is a armv7 build I thought Id use that. 

I get the following error: 

> ./dungeon-revealer-linux-armv7
> pkg/prelude/bootstrap.js:1183
>       throw error;
>       ^
> 
> Error: The module '/home/pi/Desktop/revealer/node_sqlite3.node'
> was compiled against a different Node.js version using
> NODE_MODULE_VERSION 72. This version of Node.js requires
> NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
> the module (for instance, using `npm rebuild` or `npm install`).
>     at Object.Module._extensions..node (internal/modules/cjs/loader.js:729:18)
>     at Module.load (internal/modules/cjs/loader.js:610:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:549:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:541:3)
>     at Module.require (internal/modules/cjs/loader.js:648:17)
>     at Module.require (pkg/prelude/bootstrap.js:1164:31)
>     at require (internal/modules/cjs/helpers.js:20:18)
>     at Object.<anonymous> (/snapshot/app/node_modules/sqlite3/lib/sqlite3-binding.js:4:15)
>     at Module._compile (pkg/prelude/bootstrap.js:1259:22)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:711:10)

So I guess I have the wrong node.js version? Using NVM and the modules list [here](https://nodejs.org/en/download/releases/) I tried both Node.js 12.18.2 and 10.21.0. The error mentioned above was always the same. So I am stuck, far beyond my skills. Any Idea what I am doing wrong? I'd very much appreciate if you have the time to look into it.

Kind regards

**Comment by n1ru4l** [comment]
The Node.js Version is bundled with the binary. It seems like there is an issue with while the binary is packaged.

**Comment by n1ru4l** [comment]
@hinjodragonfly I created https://github.com/dungeon-revealer/dungeon-revealer/issues/551 for tracking this issue.

**Comment by maxb2** [comment]
The docker version for the raspberry pi works correctly if you need it right away.

**Comment by n1ru4l** [comment]
v1.8.1 should resolve this issue: https://github.com/dungeon-revealer/dungeon-revealer/releases/tag/v1.8.1

**Comment by hinjodragonfly** [comment]
Yes, it does work now. 

Now I just have to find out why the player-view keeps crashing on chromium on the raspberry pi when a newly revealed section is sent. 

Thank you so much for your great work!

**Comment by n1ru4l** [comment]
@hinjodragonfly Is there any error appearing in the dev tool logs? https://developers.google.com/web/tools/chrome-devtools/open

**Comment by hinjodragonfly** [comment]
Hhm not really. Just says it disconnected?

![photo5203909704890298270](https://user-images.githubusercontent.com/58919182/87052888-99d74800-c201-11ea-9f64-245901a7ccb2.jpg)

**Comment by n1ru4l** [comment]
I think that could be related to https://github.com/dungeon-revealer/dungeon-revealer/pull/454/files as the hardware of the raspberry pi might struggle with that (iPad and iPhones do so too). I might revert that before I completely rewrite the map view to be more performant.

**Comment by hinjodragonfly** [comment]
It definitely also occured with smaler Maps (for example, 904x1280px, 167kb) - and the latest version it worked was with v1.5.0 (which I ran through yarn I think)...after that came COVID-19 and I never tried a later version until this week.

**Comment by n1ru4l** [comment]
@hinjodragonfly Have you tried using a different browser? How up2date is your chromium? What are the specs of your pi?

**Comment by hinjodragonfly** [comment]
Hej @n1ru4l 
Sorry for being absent.
I actually tried Firefox, Luakit, Midori...
Dungeon Revealer did not work with any of them.

Chromium is on version 74.0.3729.157. Hardware specs are a [raspberry pi 3 b](https://www.raspberrypi.org/products/raspberry-pi-3-model-b/) 
Quad Core 1.2GHz Broadcom BCM2837 64bit CPU
1GB RAM

**Comment by n1ru4l** [comment]
@hinjodragonfly I will try to test dungeon-revealer on my raspberry pi soon and investigate 👍 Sorry for the inconveniences!

**Comment by hinjodragonfly** [comment]
I am really humbled by the amount of your free time you invest in this problem. It's rather the opposite of inconvenient. Thank you so much!

**Comment by n1ru4l** [comment]
@hinjodragonfly So I set up my raspberry pi 3 with the default os + docker and pulled `dungeonrevealer/dungeon-revealer:v1.9.0`.

I am not having any issues.

I connected via remote desktop as I don't have a spare HDMI cable for the TV, visited the website on chromium and put it into fullscreen mode 😅

![image](https://user-images.githubusercontent.com/14338007/87850730-b99df880-c8f2-11ea-983f-f722248fd66f.png)



Could you share the raw image you try to display? Maybe the one I choose did not cause any issues because it was too small.

**Comment by hinjodragonfly** [comment]
Hej!

Well thank you for trying :). Its more than I could ask.

I just reinstalled raspbian (to get rid of anything I might have fucked up)
- Installed nodejs version 10.21.0 & npm 6.14.4
- got docker (yay, new tool to learn)
- pulled and started Dungeon Revealer through docker

same problem -  disconnects and since the newest version freezes, or just shows no map at all.

downloaded it manually and started it

same problem

I did use [this image](https://images.squarespace-cdn.com/content/v1/51eac77ee4b008669755d740/1462222330464-5OHP8USWZ81F1LROVMKC/ke17ZwdGBToddI8pDm48kN7UInCDy43kaPTfnfjld6h7gQa3H78H3Y0txjaiv_0fmUlfgh0PDRwdBlKSZS7d3nCTL5zGFV3pRABxbZxr2Z8BgMhpGzkN_zMfv4cjnhJjeoqS5JAWrnb1436X_b_yVZ5uBJOnOmCWBN4JfYsIDySKIn0wJWsAT2B2aOu794dDDF5lN9ADtKpdIDtRvrY2Hw/image-asset.jpeg) first, but basically tried one larger with 2mb and one lower with around 200kb.
It really doesn't matter to much. 

There are no other applications running other than chromium ofc.

I also launched DR through my desktop-PC with the map from above. When I enter DR through the Raspberry as player it also genereally disconnects first, then loads but it is kind of unstable, sometimes freezes or show no map.

- I doubt it is a hardware problem - according to the task manager I am never higher than 55% CPU usage and I always have around 300mb memory left. No idea how accurate that is.
- Strange detail: Running DR on the raspberry but the viewer on the desktop goes rather smoothly (also with the 2mb map), the other way around it might freeze or disconnect -> the problem seems to be the player section?
- If you have any other things you think I should test I will when I have the time (E.g. I could try to run an older version with yarn and see if that still works)

Thank you for your time!
Kind regards.

**Comment by n1ru4l** [comment]
@hinjodragonfly could you try the `master` branch? (Docker Image: `dungeonrevealer/dungeon-revealer:dev`)

**Comment by n1ru4l** [comment]
@hinjodragonfly https://github.com/dungeon-revealer/dungeon-revealer/issues/606

**Comment by hinjodragonfly** [comment]
Alright alright alright. I did not have time to test out many combinations, but...

It works. A bit slow but I could get the player view on the Raspberry and it did not crash or freeze or show only black. Even did it with a 1,9mb map. DM Section on my Lenovo Tablet on Firefox. 

What was a bit weird: The player section showed the map verticall mirrored, and zooming through mouse wheel was inverted as well?
When I loaded the DM Section on the raspberry as well as the player section, it froze again. Gonna try around some more tomorrow.

**Comment by n1ru4l** [comment]
The dm map view is still the old implementation. The vertical mirroring is a bit weird does it happen for all images? Maybe die metadata of the image (orientation) is wrong

**Comment by hinjodragonfly** [comment]
I tried 3 different images, it was always mirrored. Maybe its chromium?
btw one of the images was 14,8mb and it went rather smoothly :)

Another small thing: in the player section there is this bar with center/+/- map. When fullscreened in chromium this bar does not stay on the left bottom but moves circa the amount of space upwards, that fullscreen adds.

I really love DR and thank you so much for your great help!
Kind regards
Sebastian

**Comment by n1ru4l** [comment]
> Another small thing: in the player section there is this bar with center/+/- map. When fullscreened in chromium this bar does not stay on the left bottom but moves circa the amount of space upwards, that fullscreen adds.

You should be able to move/drag it around.

Does the mirroring happen in all browsers?

**Comment by n1ru4l** [comment]
@hinjodragonfly Could you try this: https://github.com/cncjs/cncjs/issues/590#issuecomment-614552727

**Comment by n1ru4l** [comment]
Just double-checked on my Pi, had the same issue and the instructions fixed it.

I created an issue for adding these instructions to our docs: https://github.com/dungeon-revealer/dungeon-revealer/issues/623

Gonna close this issue for now, as the critical parts are now fixed and dungeon-revealer should now be usable on a pi + display for players.

Feel free to open a new issue for any further issues you are experiencing and thanks for your patience and feedback 😊.

I hope you enjoy using it for your games 😊

**Comment by hinjodragonfly** [comment]
I did and I will again!
Thank you so much!
