### ISSUE TITLE
travis: Github Deploy api key missing

### ISSUE THREAD

**Issue by maxb2** [dungeon-revealer/dungeon-revealer#258]
Since the switch to the organization, the `GITHUB_OAUTH_TOKEN` variable has not been set in travis. This makes any tagged build fail on the github deploy job and the dockerhub deploy job is never attempted. [See here](https://travis-ci.com/dungeon-revealer/dungeon-revealer/jobs/249903411). As a result, the latest tag on dockerhub has been stuck at v1.3.1. I manually ran the v1.5.0 dockerhub deploy job so that the latest docker image is up to date.

We need to setup an access token for travis as we did in #56. @apclary or @n1ru4l, can you take care of this?

**Comment by n1ru4l** [comment]
@apclary could you please tackle this issue?

**Comment by apclary** [comment]
@n1ru4l I'll take a look.

**Comment by apclary** [comment]
@maxb2 I guess I'm a little confused about the problem. I cycled the `GITHUB_OATH_TOKEN` in Github. Then I went to travis under my apclary account and noticed the GITHUB_OATH_TOKEN was already specified. I updated the value anyway since I had cycled away the old token.

In the logs from the latest build, I see this:
```
Setting environment variables from repository settings
$ export GITHUB_OAUTH_TOKEN=[secure]
$ export DOCKER_USERNAME=apclary
$ export DOCKER_PASSWORD=[secure]
```

From one of the recent builds, #780.3, I see this:
```
The command "docker build -t $DOCKER_USERNAME/dungeon-revealer:dev ." exited with 0.
0.07s$ docker images
REPOSITORY                 TAG                 IMAGE ID            CREATED                  SIZE
apclary/dungeon-revealer   dev                 337aa08b7ab9        Less than a second ago   611MB
node                       10-alpine           d32bf7fc7d5f        13 days ago              80.5MB
```

Maybe there's something I've missed.

**Comment by maxb2** [comment]
Maybe you're looking at the old repository or a fork on travis? The [dungeon-revealer/dungeon-revealer](https://travis-ci.com/dungeon-revealer/dungeon-revealer) repo has only had 247 builds. 
[Build #106.3](https://travis-ci.com/dungeon-revealer/dungeon-revealer/builds/133708793) for v1.5.0 failed because of this. The issue is only a problem for tagged builds.

**Comment by apclary** [comment]
@maxb2 Yeah I must have been looking at the wrong thing. I added the environment variable. Let me know.

**Comment by maxb2** [comment]
I'll make a temporary tag to test it out.

**Comment by maxb2** [comment]
It's working again. Thanks for taking care of this!
