### ISSUE TITLE
Failing build

### ISSUE THREAD

**Issue by n1ru4l** [dungeon-revealer/dungeon-revealer#268]
https://travis-ci.org/dungeon-revealer/dungeon-revealer/jobs/637629565?utm_medium=notification&utm_source=github_status

Any ideas why this is failing 😕? @apclary @maxb2

**Comment by maxb2** [comment]
That was the build for the temporary tag I made for #258. It ran once and successfully made a draft release with the binaries uploaded to it. I deleted the draft and the tag after that. This build must have been restarted after that. Really weird. It doesn't affect anything on master, so I think it's safe to ignore.

**Comment by n1ru4l** [comment]
Alright 👌
