### ISSUE TITLE
Travis Configuration

### ISSUE THREAD

**Issue by maxb2** [dungeon-revealer/dungeon-revealer#269]
I think I found the different build numbers in #258. On pull requests there are two checks that must be passed.

![travisci](https://user-images.githubusercontent.com/9096667/72905225-ccde5b80-3cf5-11ea-8089-3b1ad442c5b4.png)

Both of these checks are running the same jobs, but the build numbers in [Travis CI - Pull Request](https://travis-ci.com/dungeon-revealer/dungeon-revealer/builds/145573787) are much lower than the ones in [continuous-integration/travis-ci/pr](https://travis-ci.org/dungeon-revealer/dungeon-revealer/builds/640481602?utm_source=github_status&utm_medium=notification). Going directly to the [repository](https://travis-ci.com/dungeon-revealer/dungeon-revealer) on travis leads to the builds created by "Travis CI - Pull Request". Maybe the travis configuration on github got messed up or duplicated when we migrated to an organization.

**Comment by apclary** [comment]
Hmm, one is travis-ci.com and the other is travis-ci.org. I wonder if this is some effect of the two domains merging. I'm scared to delete one in case they are really referencing the same thing and that might cause both to be lost, but if someone is confident that's not the case please let me know.

**Comment by maxb2** [comment]
This has come up again in #212. One of the checks is stuck on pending. 

![Screenshot from 2020-03-21 08-30-27](https://user-images.githubusercontent.com/9096667/77227448-80c16300-6b4e-11ea-8d04-1c8d53eca149.png)

I went to both .com and .org and they all finished successfully. I tried restarting the build on both sites. On travis-ci.org I couldn't restart the build because I no longer have admin rights. I think it's because I'm an outside collaborator now in the organization. I was still able to restart the build on travis-ci.com though. The check is still pending.

**Comment by maxb2** [comment]
Travis has been [migrating everything](https://devops.stackexchange.com/a/4305) from .org to .com, including open source repos. Here is a [link](https://docs.travis-ci.com/user/migrate/open-source-repository-migration) to the changes that must be made. TLDR: the "Travis CI - " check is the one we should use.

**Comment by n1ru4l** [comment]
The check was required previously, but I removed it from the "pull request required check" list. However, it is stuck there. Pushing an empty commit will probably solve it.

**Comment by maxb2** [comment]
I'll close this since you removed the offending check from future builds. You can still merge because the real check succeeded.
