### ISSUE TITLE
Add support for only listening on localhost

### ISSUE THREAD

**Issue by jonhoo** [dungeon-revealer/dungeon-revealer#289]
I like to place all web-facing things behind an nginx reverse proxy, but when I run `dungeon-revealer` it currently binds the DM view to localhost and the player view to _all public IP addresses_. It'd be great if there was an option to _only_ listen on localhost for both, and then I could use nginx to route the requests.

**Comment by n1ru4l** [comment]
We could allow overriding the bind target via an environment variable.

If you already use Nginx as a reverse-proxy you could probably also configure your firewall.

**Comment by jonhoo** [comment]
That assumes I am running a firewall in the first place -- I generally try to make sure I don't have any open ports at all except 80/443/22. But yes, that'd be doable. It'd probably be preferable to have it listen only on localhost and then do the forwarding as desired though so as to not accidentally end up with exposed ports.

Personally I'd probably prefer a command-line argument, but an environment variable would also work I suppose.

**Comment by n1ru4l** [comment]
I did some double-checking and both the DM and the player view are bound to `0.0.0.0`. However, the message in the terminal shows the local network IP to make it easier for non-technical players to join.

There is currently no restriction on who is allowed to access what.

I would propose that we add an option to overwrite the host the HTTP/WebSocket server binds to.

If someone wants to restrict the players from accessing the DM section he can use the `DM_PASSWORD` and `PC_PASSWORD` environment variables.

In case someone wants to restrict access further based on the IP: It should be handled in User-Land (e.g. with a reverse proxy).

@jonhoo What do you think?

**Comment by jonhoo** [comment]
Yeah, being able to override the host seems plenty sufficient! That way I can just bind to `localhost` and direct the reverse proxy at `127.0.0.1` without worrying about additional externally-exposed ports.
