### ISSUE TITLE
Cursor sometimes gets stuck in pan mode

### ISSUE THREAD

**Issue by jonhoo** [dungeon-revealer/dungeon-revealer#293]
To reproduce:

 1. Open a map in the DM view. Notice the "pan" cursor style.
 2. Select the "mark" tool.
 3. Click the map to check that it works. Notice the "mark" cursor style.
 4. Open another application window. Place it over the browser window.
 5. Position the cursor somewhere in the other application that overlaps with the map.
 6. Use Alt-Tab to switch to the browser window without moving the cursor.
 7. Notice that the cursor briefly is in the "pan" style before changing back to the "mark" style.
 8. Repeat until the cursor gets stuck in the "pan" style. At this point you cannot get it to return to "mark" style except by refreshing the page.

I'm on Linux, and the two windows are on different virtual desktops, which may or may not matter. My reproduction is therefore _slightly_ different, and I tried to approximate it for a "normal" window manager above. My "real" reproduction in case it matters is the same as above, except that instead of overlapping the two windows, I have them on two different virtual desktops, and I switch to the browser's virtual desktop with the other application (on a different virtual desktop) as the active window.

I _suspect_ this has something to do with dungeon revealer's mouse tracking. Maybe it's using `onmouseenter` or something which doesn't trigger in this case? Not sure. If more info would be useful, let me know!

**Comment by n1ru4l** [comment]
@jonhoo I am having a hard time reproducing this on Mac OSX 😕. Could you please share a short Screen recording?

**Comment by jonhoo** [comment]
Sure thing! [Here](https://jon.thesquareplanet.com/share/dungeon-revealer-issue-293.mp4). I also discovered #318 in the process (and posted a video of that).

Note that my hotkey for switching virtual desktops is Alt + <desktop number>, so Alt will be held down when the window gets focus. Not sure if that might be part of it. I also found that pressing Alt again with the revealer open exits pan mod and allows me to use the tools as expected again.

**Comment by n1ru4l** [comment]
Yeah, it is definitely related to the alt key, as I cannot reproduce it :D

I will check the event handlers

**Comment by jonhoo** [comment]
Ah, that fix makes so much sense! I wonder, do you think we should do the same on `focus`?

**Comment by n1ru4l** [comment]
@jonhoo In my testing `blur` was sufficient and consistent enough. What are your concerns for also resetting the value on a `focus` event?

**Comment by jonhoo** [comment]
No rational concern, just paranoia :)
