### ISSUE TITLE
Moving cursor while zooming leads to cursor position mismatch

### ISSUE THREAD

**Issue by jonhoo** [dungeon-revealer/dungeon-revealer#318]
See [this screen capture](https://jon.thesquareplanet.com/share/dungeon-revealer-issue-318.mp4).

**Comment by n1ru4l** [comment]
I figured out what is wrong here. Will try to create a fix tomorrow, the DM Section still uses the old implementation of the pan-zoom view which is performing a bit poorly and is also clumsy to sync state with react. The whole replacement will probably not make it into 1.6 but a quick fix should be possible.
