### ISSUE TITLE
In DM section, tool becomes stuck on move, after switching focus to different window and back to DR

### ISSUE THREAD

**Issue by mbraakhekke** [dungeon-revealer/dungeon-revealer#339]
In the DM section, switching focus to a different application and then back to the browser with DR, results in the move tool being active (hand icon), irrespective of which tool was previously selected. Clicking the buttons doesn't change this, only a full refresh (F5) fixes it.
I'm using DR 1.5 (but I saw the same behavior with 1.4) on Windows 10 x64. I've tested it in Firefox, Edge, & Chrome.

Other than that awesome app! I'm considering learning Java/Type-script so I can contribute.

**Comment by n1ru4l** [comment]
I think this is a duplicate of a duplicate of https://github.com/dungeon-revealer/dungeon-revealer/issues/293 and should already be fixed on the master branch

**Comment by mbraakhekke** [comment]
Thanks! Eagerly awaiting v1.6 then!
