### ISSUE TITLE
Player connection fails to show map when password protected

### ISSUE THREAD

**Issue by Milibar** [dungeon-revealer/dungeon-revealer#365]
Hi,

I have found that when the player side is password protected it no longer updates from the server.

Server Raspberry Pi 4
Client Firefox tested in private mode
Client Chrome tested in incognito mode

Happy to help investigate.

PS love the system and hope it keeps moving forward, thank you

**Comment by n1ru4l** [comment]
@Milibar Thanks for the bug report! A fix is already on its way! https://github.com/dungeon-revealer/dungeon-revealer/pull/366. Gonna release 1.6.1 soon 😇
