### ISSUE TITLE
Current user count

### ISSUE THREAD

**Issue by Milibar** [dungeon-revealer/dungeon-revealer#376]
Hi,

Loving the program and many cool ideas listed.

Suggestion, add current players and DM's counter to the top right of the display?

Thank you for all your work and have a good day

Andrew

**Comment by n1ru4l** [comment]
Hey @Milibar, that is indeed a nice idea! I am planning on adding a (dice roller) chat soon, so people will also be able to set their display name, this would be a nice addition 👍

**Comment by n1ru4l** [comment]
@Milibar I am implementing this as part of https://github.com/dungeon-revealer/dungeon-revealer/pull/403 I just added some screenshots about the feature and if possible would welcome any feedback 😊

I will try to cut out 1.8 this or next weekend!

**Comment by n1ru4l** [comment]
Implemented as part of #403
