### ISSUE TITLE
Shutdown hangs while clients are open

### ISSUE THREAD

**Issue by jonhoo** [dungeon-revealer/dungeon-revealer#389]
If I try to close the server while someone still has a tab with Dungeon Revealer open, it prints
```
^CShutting down
```
But then just hangs forever. When the last client is eventually closed, it does shut down after a few seconds. Is this intended behavior? It seems useful to be able to shut down the server without having to make sure all players and the DM have closed their sessions. It's pretty easy to forget you have it open somewhere in the tab all the way over there.

**Comment by n1ru4l** [comment]
I also noticed that and it is most likely related to socket.io or http.Server

https://github.com/socketio/socket.io/issues/1602#issuecomment-120561951
