### ISSUE TITLE
ISC licensed, but not license file

### ISSUE THREAD

**Issue by jonhoo** [dungeon-revealer/dungeon-revealer#390]
When packaging this for Arch, I discovered that the [ICS license](https://opensource.org/licenses/ISC) (like the MIT and BSD licenses) actually require a license file for each project, since they contain the author name and year. Would you mind adding a LICENSE file to the repository so that that can be distributed with the package?

**Comment by n1ru4l** [comment]
@jonhoo Can we just copy https://github.com/n1ru4l/use-async-effect/blob/master/LICENSE over here and change and replace author/year, must this be done by @apclary? Could I do it? Could I add his and my name, as he is not that active anymore? 

This seems also like a possible solution:
https://github.com/emotion-js/emotion/blob/master/LICENSE

**Comment by jonhoo** [comment]
You cannot change the license without consent from the original author I think. They chose the ICS license, and so you'd need to copy in that license file (see the link in my post). I don't actually know the rules around what name to add given the change of ownership.

The ISC license seems quite permissive, though it does require that you include the original license notice. Not sure how that affects your ability to re-license. May be worth doing a quick Google search for relicensing?

**Comment by n1ru4l** [comment]
I changed it to ISC
