### ISSUE TITLE
Release binary has some issues

### ISSUE THREAD

**Issue by jonhoo** [dungeon-revealer/dungeon-revealer#391]
I don't know if there's anything to really do about these, but figured I'd flag them just in case.
When packaging for Arch, I noticed these warnings from the packaging linter:
```
dungeon-revealer-bin W: ELF file ('usr/bin/dungeon-revealer-linux') lacks FULL RELRO, check LDFLAGS.
dungeon-revealer-bin W: ELF file ('usr/bin/dungeon-revealer-linux') is unstripped.
dungeon-revealer-bin W: ELF file ('usr/bin/dungeon-revealer-linux') lacks PIE.
dungeon-revealer-bin W: Unused shared library '/usr/lib/librt.so.1' by file ('usr/bin/dungeon-revealer-linux')
```
If I try to strip the binary, it fails to run with `Pkg: Error reading from file.`, which makes me think this is definitely some kind of special binary. So all the warnings above may not _really_ apply.

**Comment by jonhoo** [comment]
If you're curious, the package is up at https://aur.archlinux.org/packages/dungeon-revealer-bin/ :)

**Comment by jonhoo** [comment]
(it is `-bin` because it uses the binary build artifact rather than building from source)

**Comment by maxb2** [comment]
I found [this](https://bbs.archlinux.org/viewtopic.php?id=240279) for `RELRO` and `PIE`. I don't know if it helps though.

**Comment by n1ru4l** [comment]
Is this something that must be fixed inside [pkg](https://github.com/zeit/pkg) or by us?

**Comment by jonhoo** [comment]
Not sure actually. My _guess_ would be in pkg.

**Comment by n1ru4l** [comment]
I’m gonna close this issue for now, as mentioned before, this is something that should be addressed in pkg
