### ISSUE TITLE
Actions jobs doubled for Renovate

### ISSUE THREAD

**Issue by maxb2** [dungeon-revealer/dungeon-revealer#395]
Since Renovate makes a branch in this repo and then immediately opens a pull request, those renovate branches are being checked twice. It's significantly slowing down the queue.

**Comment by n1ru4l** [comment]
I think we can filter the pull request branches

**Comment by maxb2** [comment]
Yes. I think the simplest approach is that we filter out the renovate/* branches and continue to check all pull requests.

There are several community actions to cancel workflows. I'll look to see if any of them suit our project.

**Comment by n1ru4l** [comment]
Any concerns regarding limiting the workflow to be triggered through push on master only + pull request update?

**Comment by maxb2** [comment]
I think it would be better to just filter out the `renovate/*` branches. We know those will always be opened as a pull request.
