### ISSUE TITLE
Quick-export map from DM screen

### ISSUE THREAD

**Issue by jonhoo** [dungeon-revealer/dungeon-revealer#414]
I'm considering starting to run my games over Discord (slyflourish has a [cool video on it](https://www.youtube.com/watch?v=_Yg-GyrcccI)) using the [Avrae D&D bot](http://avrae.io/). One thing the bot is missing though is the ability to show combat maps, and I figured I might be able to use dungeon-revealer to bridge that gap.

While it'd be nice to have bot integration, I think that's probably outside the scope of this tool. Instead, it would be really helpful if there was a quick way to export/copy the player view of the current map from the DM view. That way I could just paste that map into Discord, and players wouldn't have to leave it at all. Given how dungeon-revealer currently operates, I _think_ this is just a matter of adding a button that links to an endpoint that serves the current map merged with the current fog as a single jpg? I could then just click that button, copy/save the image, and paste. Done!

Probably low priority, but it would make this tool work super nicely with Discord!

**Comment by n1ru4l** [comment]
Backend changes might not even be required as we could just write the stuff to a  canvas and copy the blob to the clipboard https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/write

**Comment by n1ru4l** [comment]
@jonhoo You might wanna check out https://github.com/dungeon-revealer/dungeon-revealer/pull/415
