### ISSUE TITLE
release 1.7.x changelog

### ISSUE THREAD

**Issue by n1ru4l** [dungeon-revealer/dungeon-revealer#426]
This is the WIP changelog for version 1.7.0

# What is new?

## Features

- **Support more docker platforms**: The pre-built docker images now target even more platforms. You can now spin up dungeon-revealer on `linux/amd64`, `linux/386`, `linux/arm/v6`, `linux/arm/v7` and `linux/arm64` architectures. (https://github.com/dungeon-revealer/dungeon-revealer/pull/407)
- **Media Library**: You can now import any image into the media library which allows you embedding the images inside your notes and sharing them with the players. This is way more convenient than loading a new map. (https://github.com/dungeon-revealer/dungeon-revealer/pull/370)
- **Import map via Drag&Drop**: Import maps more easily by simply dragging them into your browser window! (https://github.com/dungeon-revealer/dungeon-revealer/pull/420)
- **Export player map as image**: The current player map can now be exported as an image. On modern Browsers, the image will be automatically copied to your Clipboard. On older browsers, the image will be opened in a new tab and you must manually store it on the filesystem/copy it to your clipboard. (https://github.com/dungeon-revealer/dungeon-revealer/pull/415, https://github.com/dungeon-revealer/dungeon-revealer/issues/414)
- **Use filename as default map name**: Often the map filename is already descriptive enough. When importing a map you must no longer re-type the filename, but you can still change it 😉.(https://github.com/dungeon-revealer/dungeon-revealer/issues/384)

## Fixes

- **Shutdown Hangs due to open connections**: Prior to this fix, the server would not close open connections when initiating a graceful shutdown (https://github.com/dungeon-revealer/dungeon-revealer/pull/397, https://github.com/dungeon-revealer/dungeon-revealer/issues/389)

# Install

Download a release below for your platform or [check out the install instructions](https://github.com/dungeon-revealer/dungeon-revealer/tree/v1.7.0#getting-the-app)

# What is up next?

You can check out the milestones over here: https://github.com/dungeon-revealer/dungeon-revealer/milestones. Do you think something is missing? Feel free to open new issues and propose new features or report bugs!

The next version `1.8.0` will make remote playing even easier by proving a chat with dice rolling capabilities!

**Comment by KoenR3** [comment]
I do not see any docker images for version 1.7 currently?

**Comment by KoenR3** [comment]
Nevermind, I see the releases disappeared from the releases page.

**Comment by n1ru4l** [comment]
Yeah we are having some issues rn with the binaries

**Comment by n1ru4l** [comment]
1.7.2 is now released https://github.com/dungeon-revealer/dungeon-revealer/releases/tag/v1.7.2
