### ISSUE TITLE
Dragable tokens from the Playerview

### ISSUE THREAD

**Issue by k3tw13z3l** [dungeon-revealer/dungeon-revealer#439]
Hi,

Love the new release!

Before the Covid Lockdown we used the program on a monitor at the table and used miniatures, but now with the need for remote play, I've got a request:

If for the next 1.8. milestone remote playing is a focus, I would like to see the option on a token that it is 'player' movable... I saw it was suggested in the original #35 issue, so maybe it is already discussed and off the table so to speak.... :smile: Then no worrries and you can close this.

**Comment by n1ru4l** [comment]
This seems like a good idea and shouldn't be that hard to implement since we just need to re-use existing functionality.

**Comment by nickguiliani** [comment]
Has there been any motion on this. I use the program for the games i run at my local gamestore. Would love for the players
to be able to move their own characters. As well as use a hyperlink to store their DnD beyond character sheet to the token would be helpful

**Comment by k3tw13z3l** [comment]
No, I've been looking at the code myself and trying to figure out where to start, but the typescript/react has not yet made a connection with my brain...

Hyperlinks do not (yet?) work in the rendered version of the note, but I saw some changes that allows more HTML in the rendered output.. (In the edit mode the editor allows you to follow the link)

**Comment by nickguiliani** [comment]
Ok, Good to note.
Question, would it be an easy placeholder to allow players to ping or mark the map so the DM would know where the players
wish their token to move.

**Comment by n1ru4l** [comment]
@k3tw13z3l @nickguiliani Hey there!

I am currently focused on improving the note-taking experience and knowledge base experience (see https://github.com/dungeon-revealer/dungeon-revealer/pull/530). Afterward, my main focus will be re-designing everything related to tokens and maps.

>Question, would it be an easy placeholder to allow players to ping or mark the map so the DM would know where the players
wish their token to move.

This is already possible by doing a long-press on a section of the map. (Not easy to discover TBH, I am open for better suggestions for making this easier).

Moving the tokens themselves is also something my players requested heavily and something that will definitely be part of dungeon-revealer in the future!

> No, I've been looking at the code myself and trying to figure out where to start, but the typescript/react has not yet made a connection with my brain...

I must also admit that the current implementation is a bit hard to understand and I will try to do my best in making it easier to understand in the future 😅.

Thank you for providing me feedback and of course using dungeon-revealer!

**Comment by nickguiliani** [comment]
@n1ru4l 
Thanks for the quick response.
My setup is a Surface Pro 7 hooked up to a TV or Projector. My players either use a tablet for DnD beyond character sheets or a laptop. 
It has been hard to find anything on how the system works as there does not seem to be any direct help section. I would be open to the idea of making tutorial videos to help people see what all is possible in the software.

is there a way to get mobile devices to be able to connect to the server machine? some players use tablets and the normal connection route does not seem to work for them.

**Comment by n1ru4l** [comment]
> is there a way to get mobile devices to be able to connect to the server machine? some players use tablets and the normal connection route does not seem to work for them.

As long as the devices are in the same network that should be possible by using the public IP (unless your device where dungeon-revealer is running on has a strict firewall.

> It has been hard to find anything on how the system works as there does not seem to be any direct help section. I would be open to the idea of making tutorial videos to help people see what all is possible in the software.

Could you brainstorm some ideas on what in particular you think is hard to discover/use?

I also created this discord server a time ago, but never really used it. It might be easier chatting a bit over there instead of writing down everything here. https://discord.gg/ypDpJM

**Comment by n1ru4l** [comment]
@nickguiliani @k3tw13z3l This will be part of v.1.9.0 which comes out this weekend 😉

See https://github.com/dungeon-revealer/dungeon-revealer/pull/562
