### ISSUE TITLE
Drag & drop token issue when changing map

### ISSUE THREAD

**Issue by GoOz** [dungeon-revealer/dungeon-revealer#449]
I have an issue while dragging token after changing maps.
[A video is better than words](https://www.foojin.com/dropbox/dragdroptoken.mp4)

It occurs on latest FF and Chrome.

It's not blocking as it fixes itself when I reload the page but still, it's an odd behaviour.

I don't know if it's due to a difference of image size but my first map is huge, the next one not so much.

**Comment by n1ru4l** [comment]
possible regression of https://github.com/dungeon-revealer/dungeon-revealer/issues/356

**Comment by n1ru4l** [comment]
@GoOz I tried multiple map sizes and cannot reproduce this 😕

Could you please share the exact image sizes?

**Comment by GoOz** [comment]
Ok after a little investigation on my side, this has nothing to do with the previous image size, sorry.

But if you load a big map, all the new tokens you create have the bug until you refresh the page.
Weirdly, if I add a token it will be bugged and then I refresh so this token won't be bugged anymore BUT if I add a new one, it will be bugged too while the first is fixed. :o 

I had the bug with those map sizes : 
- 5641 × 7906
- 6000x3000
- 7200x7200

But I found out that a map of 3000x3000 doesn't bug and when I enhance it to 3050x3050 it starts to bug (very lightly as it seems that the offset increase as the map size increases)

So the bug definitely starts à 3000px.

**Comment by n1ru4l** [comment]
@GoOz Could you please check whether https://github.com/dungeon-revealer/dungeon-revealer/pull/453 does resolve this issue? I was able to reproduce the issue and these adjustments did work for me.

**Comment by GoOz** [comment]
@n1ru4l It works just fine now 👍 
Thank you.
