### ISSUE TITLE
List items not working in Notes

### ISSUE THREAD

**Issue by k3tw13z3l** [dungeon-revealer/dungeon-revealer#532]
```
- text
- text2
```
gets rendered as:

text text2

?

**Comment by n1ru4l** [comment]
That is because it is interpreted as a HTML tag and therefore stripped out by our sanitize function. Wrapping it in backticks should work.

**Comment by n1ru4l** [comment]
Also I am currently updating the list of allowed HTML/markdown tags so lists tables etc should work as expected soon.
