### ISSUE TITLE
Map persistence when losing focus

### ISSUE THREAD

**Issue by cbaijens** [dungeon-revealer/dungeon-revealer#555]
Since V1.8.0 I've noticed a slight issue.
Half the time I'm using a local setup where as a DM I'm using a laptop connected to a secondary monitor. The monitor is placed flat on the table showing a browser window with the "Player" screen. On my own screen I'm controlling the DM screen. However when I'm changing focus between the two windows, the unfocused one goes inactive. This also resets the zoom / focus on the player map when refocused afterwards. Is it possible to be able to retain focus on both windows?

**Comment by n1ru4l** [comment]
Have you tried open the second window in an incognito tab?

**Comment by cbaijens** [comment]
I have not! Awesome, it works exactly as I hoped! Thank you for the quick reply, awesome application!

**Comment by n1ru4l** [comment]
Glad you enjoy using this app 😍. Feel free to join our discord for questions or feedback https://discord.gg/ypDpJM
