### ISSUE TITLE
Update map grid

### ISSUE THREAD

**Issue by jonhoo** [dungeon-revealer/dungeon-revealer#559]
There isn't currently a way to update the grid settings for a given map, except by going through the whole grid setup process again. It'd be nice if there was a way to just tune it on the already-open map. I expected this to be under "Grid Settings", but that seems to only have visualization settings?

**Comment by n1ru4l** [comment]
Closed in v1.11.0, we overhauled the whole grid configurator. Instead of configuring everything from scratch, the changes can now be applied from the previous grid state.
