### ISSUE TITLE
Grid setting problematic for large maps

### ISSUE THREAD

**Issue by jonhoo** [dungeon-revealer/dungeon-revealer#560]
If you upload a large map into dungeon-revealer, and then try to set a grid, the process is pretty painful. The map isn't zoomed out in the grid view, so you're only able to set the blue box in the first step of grid setup to the top left corner of the map. This is especially problematic if the top-left corner does not have easily visible tiles to align with.

The same applies to the next step of the grid setup where you fine-tune the grid. You're locked into the top-left view, which may not be sufficient for alignment. It'd be great here if it was possible to pan and zoom the map while adjusting the grid settings, since it'd make it much easier to find settings that work across the map, not just in the one visible segment of it.

**Comment by azzco** [comment]
Adding to that, fine tuning on only a single tile can be quite hard as well as several tiles down the line it might be just a tiny bit too small or big and go out of sync with the actual map.

Being able to scale to more tiles in the second step would really help.

**Comment by n1ru4l** [comment]
Closed in v1.11.0, we completely overhauled the grid configurator. It is now possible to completely zoom in and out on every possible position on the map while configuring the grid.
