### ISSUE TITLE
allow editable default token (size/color/text)

### ISSUE THREAD

**Issue by jeffvenuti** [dungeon-revealer/dungeon-revealer#572]
I'm constantly resizing the tokens to be the same size every time I create one.  The ability to set the default size, and maybe even color and text, would save a lot of time during the token creation process.

**Comment by k3tw13z3l** [comment]
I thought it resized the token to the grid (you must have one), or am I mistaken? The grid can be set invisible for the players.

**Comment by jeffvenuti** [comment]
No, my map images already have grids on them, so I don't add a grid

So I just checked and if I add a grid then yes, a token does come in as a single grid unit size.  But I don't need to add grids to my maps.  Would be much easier if there was an option on the token edit page like "make default token".

Thanks,
Jeff


________________________________

**Comment by n1ru4l** [comment]
How would be know the size without defining the grid column dimensions first?

Every map has different dimensions, so we need a configured grid in order to size the tokens.

You can still disable the displaying of the grid. Also you will not get the snap to grid benefits for the area reveal/hide tool.

**Comment by jeffvenuti** [comment]
You've put a token size slider on the token edit menu/page.  I'm thinking I could just resize the token with that, then make that the default size for this map so that I don't have to resize every other token.

Wouldn't this work?
________________________________

**Comment by n1ru4l** [comment]
Closed in v1.11.0, we now have a menu in which it is possible to configure everything related to tokens before adding them to the map.
