### ISSUE TITLE
double click to edit token

### ISSUE THREAD

**Issue by jeffvenuti** [dungeon-revealer/dungeon-revealer#574]
It seems more natural to be able to double click on a token to edit it, rather than right click.

**Comment by n1ru4l** [comment]
The idea is to open a context menu which is afaik opened with a right click on any platform I ever used. 
But I can also understand the edit file name mentality.

**Comment by Wizard37** [comment]
FWIW -- I haven't been able to edit tokens using my iPad yet so I'm not sure if having a double-tap/click on some platforms and a right-click on others is a viable or efficient solution, but it would be a nice to have.

**Comment by n1ru4l** [comment]
The counterpart on mobile would be a long press. Right now there is no official Tablet/mobile support for the DM section. However, this is something we want to change in the upcoming 1.11.0 version. Therefore I will add this issue to the milestone.

Right-click is the default for opening a menu (which is often replaced long-press on mobile).

**Comment by n1ru4l** [comment]
Closed in v1.11.0, it is now possible to either use a right-click or a long press on the token for opening the edit menu.
