### ISSUE TITLE
New install via Docker, there is no "Dungeon Master link" anywhere

### ISSUE THREAD

**Issue by nonplayer** [dungeon-revealer/dungeon-revealer#583]
I'm brand new to using this tool, and trying it out to see if it could be good for my online games. I hit a snag almost immediately. The README says to "click on the Dungeon Master link" on the main page, but there is no such link. I can only access the DM page my manually going to address:port/dm in my browser. I am not sure if the doc is outdated, or if there is instead a problem with the "latest" docker image as dated from about 15 minutes ago.

**Comment by n1ru4l** [comment]
You are right the docs are outdated. Sorry for the inconvenience! We should fix the docs!

The link is also outputted to the terminal:

```
laurin@Laurins-MacBook-Pro:~$ docker run -P  dungeonrevealer/dungeon-revealer:v1.9.0
Unable to find image 'dungeonrevealer/dungeon-revealer:v1.9.0' locally
v1.9.0: Pulling from dungeonrevealer/dungeon-revealer
cbdbe7a5bc2a: Pull complete 
bd07af9ed1a4: Pull complete 
3556ccf180b2: Pull complete 
089d4748da74: Pull complete 
804171b4c9b8: Pull complete 
5216c1aa6a10: Pull complete 
d3be606f5cc1: Pull complete 
250940537eb0: Pull complete 
d16fc1940f69: Pull complete 
a175941f529d: Pull complete 
Digest: sha256:6d2cf9d392543bdfbf0a9424a2f4df7723024e913f5c53e467360677862bae56
Status: Downloaded newer image for dungeonrevealer/dungeon-revealer:v1.9.0

Starting dungeon-revealer.

Configuration:
- HOST: 0.0.0.0 
- PORT: 3000
- PUBLIC_URL: <none>

dungeon-revealer is reachable via the following addresses:

- http://127.0.0.1:3000
- http://172.17.0.2:3000

Player Section: http://127.0.0.1:3000
DM Section: http://127.0.0.1:3000/dm

-------------------
```

**Comment by nonplayer** [comment]
Okay I see what happened. The `docker run` command from the docs uses the `-d` flag. When pasted into the terminal and modified for local password and data dir, by default it doesn't show any of that information.

**Comment by nonplayer** [comment]
Also: thanks for the clarification!

**Comment by n1ru4l** [comment]
You should also prefer using the version tagged docker images v1.9.0 instead of latest in order you are using a stable version. @maxb2 Maybe we should have a stable tag which is an alias for the latest release?

**Comment by maxb2** [comment]
If `PC_PASSWORD` is set, then there is a DM link on the page. Otherwise it just says "Ready". I'll update the docs.

**Comment by maxb2** [comment]
As far as the docker tags go; `stable`, `latest`, and `release` are all synonyms for the latest `vX.X.X` tag. `dev` is the only tag that points to the master branch. You can compare the hashes [here](https://hub.docker.com/r/dungeonrevealer/dungeon-revealer/tags).
