### ISSUE TITLE
Public Notes seem to not do anything on the player side

### ISSUE THREAD

**Issue by nonplayer** [dungeon-revealer/dungeon-revealer#584]
New user via docker latest image, I'm curious what the purpose of "Public" notes is. I have made notes public for testing, but there are no ways I can see for the player interface to access them. I searched for a prior doc or issue but find no additional information. Hoping I'm not doing something wrong.

**Comment by n1ru4l** [comment]
@nonplayer There is a search icon next to the chat toggle icon. Public notes can be found by the search over there. Also on the dm side for public notes a share icon appears which will share the note to the chat if clicked.

The documentation could definitely be improved!

Currently, the note editor is a bit confusing. I agree with that. I am planning to improve it in the future/make it less complicated and more intuitive.

Feel free to join us on discord to discuss further things  😊

**Comment by maxb2** [comment]
@nonplayer check out the notes page in the new [wiki](https://github.com/dungeon-revealer/dungeon-revealer/wiki/Notes).

**Comment by nonplayer** [comment]
> 
> 
> @nonplayer check out the notes page in the new [wiki](https://github.com/dungeon-revealer/dungeon-revealer/wiki/Notes).

Heck yeah!

**Comment by nonplayer** [comment]
True facts about Goblins, too.

**Comment by maxb2** [comment]
@nonplayer does this answer your question? Can we close this issue?

**Comment by nonplayer** [comment]
Oh yes, my bad. Thanks for the clarification!

**Comment by maxb2** [comment]
No worries. Happy to help!
