### ISSUE TITLE
Sharing image splashes

### ISSUE THREAD

**Issue by jeffvenuti** [dungeon-revealer/dungeon-revealer#653]
I enjoyed being able to splash the players maps screen with the image of a monster, or sometimes a critical role graphic, but it seems in recent versions this has been relegated to the chat box/window.  Is there a way make the image display over their map, instead of in their chat box?  They don't necessarily have the chat box open so don't notice it there.

Thanks,
Jeff

**Comment by n1ru4l** [comment]
I agree that we should provide a way to do both! Thanks for your feedback!

**Comment by n1ru4l** [comment]
I will add this to the 1.10.3 release as we should not have changed the behavior in the first place 😅

**Comment by n1ru4l** [comment]
@jeffvenuti This is implemented as part of [1.10.3](https://github.com/dungeon-revealer/dungeon-revealer/releases/tag/v1.10.3). It is now possible to share to the chat or to splash share 😊.

**Comment by jeffvenuti** [comment]
Fantastic!  Thank you.

Jeff
________________________________
