### ISSUE TITLE
create warning when importing maps whose dimensions are not a power of 2

### ISSUE THREAD

**Issue by n1ru4l** [dungeon-revealer/dungeon-revealer#707]
It could be possible that Three.js is not able to display the texture for an image/fog if the image cannot be downscaled to the maximum WebGL texture width. This is especially an issue with larger maps.

We should encourage users to only upload maps that can be downscaled in such cases. Downscaling will result in a loss of quality but could be a possible solution for now.

A simple solution is to show a text when importing the map.

## Relevant code

**File import modal** (Shown when dragging an image into the DM section): https://github.com/dungeon-revealer/dungeon-revealer/blob/b49ade043edef35d9d39804ac45259425098b29f/src/dm-area/import-file-modal.tsx#L54

**Map library import modal** (Shown when pressing the **Create New Map** buttonon the media library view:
https://github.com/dungeon-revealer/dungeon-revealer/blob/e320684524daec275e200dc342e05e2c008f0fb0/src/dm-area/select-map-modal.tsx#L368

## Alternatives

Another solution would be adding padding (black pixels) to the width/height of the image until both values become a power of 2.

A better long term solution would be to split the map image into multiple textures that are attached to different mesh elements. It will increase the complexity of dungeon-revealer, but ensure high quality textures.

**Comment by maxb2** [comment]
We could treat large images like [tiled web maps](https://en.wikipedia.org/wiki/Tiled_web_map). We'd have to generate the tilesets at different [zoom levels](https://leafletjs.com/examples/zoom-levels/) on upload. It would certainly increase complexity, but also bring things closer to real world mapping software.

See [Leaflet](https://leafletjs.com/) and [Mapbox](https://docs.mapbox.com/studio-manual/reference/tilesets/).

*I tried making an interactive map for a West Marches campaign using [HandsOnDataViz/leaflet-storymaps-with-google-sheets](https://github.com/HandsOnDataViz/leaflet-storymaps-with-google-sheets).*

**Comment by maxb2** [comment]
Padding the image to a power of 2 sounds like a good quick fix though.

**Comment by maxb2** [comment]
Here is a [Leaflet tutorial](https://leafletjs.com/examples/crs-simple/crs-simple.html) for non-geographical maps. Perhaps there is some inspiration to be found somewhere in there.

**Comment by n1ru4l** [comment]
I think we don't need to implement this for now, as all the issues were related to accidentally upscaling images.
