### ISSUE TITLE
Document ?map_only parameter

### ISSUE THREAD

**Issue by n1ru4l** [dungeon-revealer/dungeon-revealer#711]
By appending the `?map_only` parameter the chat and note UI is hidden for the players. This can be useful in a setup with a single monitor for everyone at a table etc.

e.g. `http://localhost:3000/?map_only`.

In case there is a password set for the player section it is also possible to provide it via the `password` parameter.

e.g. `http://localhost:3000/?map_only&password=foobars`

**Comment by Jonyango** [comment]
Hey. I would love to work on this issue. Please do elaborate further on the problem statement. Thank you.

**Comment by n1ru4l** [comment]
You could add that information on the **Getting-Started** page under the Player Section. With a title such as "Hide Chat & Notes UI" (https://github.com/dungeon-revealer/dungeon-revealer/wiki/Getting-Started).

**Comment by maxb2** [comment]
Closed via #784
