### ISSUE TITLE
Update Wiki Token Page

### ISSUE THREAD

**Issue by n1ru4l** [dungeon-revealer/dungeon-revealer#768]
It is no possible to lock a token for players only. The picture is also outdated.

The wiki should be updated to include a new up2date screenshot plus a more detailed description of all the features.

**Comment by Jonyango** [comment]
Hey. I would love to help to work on this. Let me know how to proceed.

**Comment by n1ru4l** [comment]
Hey @Jonyango!

The wiki page is the following: https://github.com/dungeon-revealer/dungeon-revealer/wiki/Tokens
The corresponding file that must be edited is over here: https://github.com/dungeon-revealer/dungeon-revealer/blob/master/wiki/Tokens.md

You might start with downloading the app, creating a new screenshot of the current token menu and then document the different functionalities :).

Instead of uploading the image in the repository you can simply drop it into an comment into this issue for uploading and use the URL for referencing inside the markdown file :)

**Comment by Jonyango** [comment]
Okay. I am on it.

**Comment by Jonyango** [comment]
[
![token_menu](https://user-images.githubusercontent.com/43377714/94870263-6b0aef80-0447-11eb-8fb1-07bf663eb7a0.PNG)
](url)

**Comment by Jonyango** [comment]
I made a pull request for what I did. Looking forward to the review.
