### ISSUE TITLE
Allow players to view token notes for player movable tokens

### ISSUE THREAD

**Issue by curtp** [dungeon-revealer/dungeon-revealer#782]
It would be helpful for players to be able to view notes for tokens they are allowed to move. I'm assuming if the player can move the token, it is probably a token for their character. They could then edit the notes to track things like hit points or anything else related to their character.

**Comment by n1ru4l** [comment]
@curtp That is a great idea! Player notes in general are something I definitely wanna have in dungeon-revealer at some point. Enabling it for movable tokens would be a great first implementation.

My only concern with multiple users working on the same document at the same time would be overwrites and data-loss without some kind of operational transformation algorithm. However, the same issue exists today if you have more than one person acting as a dungeon master.

**Comment by curtp** [comment]
I'd help, but unfortunately I'm not familiar with the technology. What I've done in apps I've worked on is use optimistic locking by using a version # on the data. When updating the record, the version # is part of the query. If the version # doesn't match, the update is rejected and an error is displayed. That means someone else updated the data in the time it was retrieved and saved again.

**Comment by n1ru4l** [comment]
@curtp Sounds like a good solution that could then be replaced with a better one someday!

**Comment by n1ru4l** [comment]
Closed in v1.11.0
