### ISSUE TITLE
Performance on older Devices

### ISSUE THREAD

**Issue by alxdean** [dungeon-revealer/dungeon-revealer#783]
Is there a minimum performance level needed to run the player screens?
I tried a Gen 2 Ipad Mini and using Safari and Chrome and the screen remained white. no splash screeen, no map controls. 

I tried a surface 2 with i5-4300 CPU and 4 GB RAM runing Win 10.1909
Chrome: Splash screen, then blank white screen. no map controls. no chat box.
Edge: Splash Screen, then black screen with chat, search and Map Controls. Sending Media as splash share does not work.

Firefox: Map is loaded with full controls, but without fog. I.e. the complete map is revealed. tokens appear and can be moved. Sending Media as splash share works ok. 

The player web app seems to be rather perfomance hungry, which seems odd for loading a simple image with layers ontop.

I had hoped to use a touch screen device for the players so they can easily take control of their tokens for the more independent experience

**Comment by alxdean** [comment]
Disabling Hardware accelleration in chrome did the trick. The map loads with fog applied! Just have to wait and see if it burns out my hardware... getting hot.

**Comment by n1ru4l** [comment]
Performance is always dependent on the asset file size and device resolution.

I have no problems with running the player section both on a raspberry pi, iPad (2019), or iPhone X. I don't own any android devices I can test upon.

Safari and Chrome on iPad are literally the same. It could be possible that the iPad OS is outdated and therefore Safari does not have some APIs required for running dungeon-revealer.

It would definitely make some sense to have some kind of recommendation for the minimum requirements and the preferred browsers!
