### ISSUE TITLE
Firefox 81.0.1 issues with Fog of War

### ISSUE THREAD

**Issue by k3tw13z3l** [dungeon-revealer/dungeon-revealer#786]
Firefox 81.0.1 on windows does not show  Fog of War. The whole map is visible...

It doen't happen on linux or Mac with the same version of Firefox.

Chromium based browsers are also not effected as far as I can tell (but I haven't tested this cross OS for all possible browsers...)

**Comment by n1ru4l** [comment]
I can confirm this issue on Firefox 81 on Windows 10.

The issue occurs when the map size is (or is scaled down) to the maximum WebGL texture size.

In my case, the fog size was scaled to 12910x16384 with a maximum WebGL texture size of 16384.

After decreasing the fog size to 70% of the original (in 10% steps) to 9037x11468 the fog was shown correctly.

The same issue did not appear in Chrome on Windows 10.

I assume that the maximum WebGL texture size reported is incorrect.

**Comment by n1ru4l** [comment]
More information: https://stackoverflow.com/questions/29975743/is-it-possible-to-use-webgl-max-texture-size/29985986

**Comment by n1ru4l** [comment]
@k3tw13z3l Can you provide feedback whether https://github.com/dungeon-revealer/dungeon-revealer/pull/799 resolves this issue for you?

**Comment by n1ru4l** [comment]
The next step here will probably be trying splitting the image into multiple parts and then test whether loading multiple textures and aligning them in a grid can solve this issue. Might also be related to https://github.com/dungeon-revealer/dungeon-revealer/issues/707

**Comment by k3tw13z3l** [comment]
Sorry for the late response work caught up we me and kept me busy. I squeezed in a docker build for the fix but something went wrong with the build. so I've got to look into that and have not been able to test the fix yet.

**Comment by n1ru4l** [comment]
@k3tw13z3l That could be related to https://github.com/dungeon-revealer/dungeon-revealer/issues/794. I rebased https://github.com/dungeon-revealer/dungeon-revealer/pull/799 onto master so the app crash should be resolved.

**Comment by k3tw13z3l** [comment]
Yeah! the fog of war is fixed as far as i can see, :smile:  (I also applied #800 to get it build successfully) I'm not really a windows user but my firefox in windows is now showing the FoW fine. 

But my tokens have no text in the player view in any browser as far as I could test in this docker container (but that is probably not related...)

**Comment by n1ru4l** [comment]
@k3tw13z3l Thanks for reporting, this was actually caused by upgrading a dependency...
