### ISSUE TITLE
Add the ability to hide notes from players

### ISSUE THREAD

**Issue by AlexLeporiday** [dungeon-revealer/dungeon-revealer#979]
When preparing for a campaign it's really nice to create a bunch of notes that players can find along the way.
Currently all notes are visible to players regardless of the permissions applied to them. The permissions seem to only control if they can be shared or not.

Would it be possible to make it so notes can be hidden from players and shared with them once they find them?

**Comment by AlexLeporiday** [comment]
Issue is closed.
Turns out you have to set a DM_PASSWORD environment variable for note permissions to take effect.
Without a password all users can see all notes.
Perhaps this could be change so that note permissions are separate from the setting of a DM_PASSWORD?

Closed for now either way.

**Comment by n1ru4l** [comment]
reopened this as discussed on discord, the notes should be hidden even without setting a dm password.
