### ISSUE TITLE
Add a way to see all notes (even if they don't have an entry point)

### ISSUE THREAD

**Issue by AlexLeporiday** [dungeon-revealer/dungeon-revealer#980]
Currently when you create a note directly on a token or from within another note it is created without an entry point.
Can you add a way to see all notes and not just notes with entry points?
They appear in search but it's not always possible to know the name of the note you're looking for.

Showing all notes should still use the public/private note access so that players can see all public notes and DMs can see all notes.

![image](https://user-images.githubusercontent.com/3112539/104848854-81e22e80-58de-11eb-8d5a-fb0a3fe7c33c.png)

For a suggestion of how this UI might look or work, add a toggle/slider to the bottom of the notes list that says "Show all"

**Comment by n1ru4l** [comment]
Any ideas where we could place such a toggle?

**Comment by AlexLeporiday** [comment]
Mocked up by copy/pasting HTML from other places in your code.
It needs cleaning up.
![image](https://user-images.githubusercontent.com/3112539/105550821-c6643480-5cf9-11eb-8674-149d8b2cc1db.png)

**Comment by n1ru4l** [comment]
It requires adjusting the database queries, I already got that part covered locally, just trying to figure out how to do the frontend, that should work out!

**Comment by AlexLeporiday** [comment]
Am I correct in that the notes window is in two parts where as the database query side of things feeds both UIs?

I found _/src/dm-area/note-editor/note-editor-side-bar.tsx_ and _/src/note-search/note-search.tsx_ that seem to serve very similar purposes with slightly different buttons on show for the DM vs regular users. Is it these two files that would need changing?

**Comment by n1ru4l** [comment]
note-search is the search input that will be opened via the search icon next to the chat visibility toggle.

The search uses a different endpoint is used for the search as we have two tables one for the notes and on full text search table for the notes.

The endpoints are described with GraphQL over here: https://github.com/dungeon-revealer/dungeon-revealer/blob/8b5eb57615e12a515210eb445d461bb6f74fe909/type-definitions.graphql#L116-L117

I will change the `Query.notes` field to also have a toggle for not filtering for entrypoints

**Comment by n1ru4l** [comment]
![image](https://user-images.githubusercontent.com/14338007/105554999-c4ee3880-5d08-11eb-8ab1-cb44711d4515.png)

This is BTW an example of how we use the notes as a knowledge base. SHowing all those notes by default would make things really cluttered as we have around 10.000 notes in the database.

**Comment by AlexLeporiday** [comment]
I hadn't thought about working with a large number of notes like that.
I think it's still important to be able to find all notes but you're right in that showing all notes when there are more than 50 in the system would be very cluttered and would likely crash the UI engine from displaying so much data.

Is the notes list paginated? If there are more than, for example, 20 notes in the list can the UI start paging through them?

**Comment by n1ru4l** [comment]
> Is the notes list paginated? If there are more than, for example, 20 notes in the list can the UI start paging through them?

Yes, the list is fully paginated and will automatically fetch more items, when you scroll down.
